# Generated by Django 4.0.6 on 2022-07-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('skill_level', models.CharField(choices=[(1, 'Absolute Beginner'), (2, 'Beginner'), (3, 'Improver'), (4, 'Improver/Intermediate'), (5, 'Intermediate'), (6, 'Intermediate/Advanced'), (7, 'Advanced'), (8, 'Advanced+')], default=1, max_length=4)),
                ('counts', models.IntegerField()),
                ('walls', models.IntegerField()),
                ('style', models.CharField(choices=[('n/a', 'Not Specified'), ('cc', 'Cha Cha'), ('chl', 'Charleston'), ('cont', 'Contemporary'), ('ecs', 'East Coast Swing'), ('fox', 'Foxtrot'), ('hh', 'Hip-Hop'), ('dsc', 'Hustle/Disco'), ('nc2', 'Nightclub Two Step'), ('plk', 'Polka'), ('qs', 'Quickstep'), ('rmba', 'Rumba'), ('sal', 'Salsa/Mambo'), ('sba', 'Samba'), ('tgo', 'Tango'), ('2st', 'Two Step'), ('vw', 'Viennese Waltz'), ('wtz', 'Waltz'), ('wcs', 'West Coast Swing'), ('oth', 'Other')], default='n/a', max_length=10)),
                ('content', models.TextField()),
            ],
        ),
    ]
