# Generated by Django 4.0.6 on 2022-07-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sheet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250)),
                ('type', models.CharField(choices=[('d', 'Demo'), ('m', 'Music'), ('w', 'Walk Through'), ('t', 'Full Teach')], default='d', max_length=3)),
            ],
        ),
    ]
