# Generated by Django 4.0.6 on 2022-07-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='video',
            field=models.ManyToManyField(to='main_app.video'),
        ),
    ]
