# Generated by Django 4.0.6 on 2022-07-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_sheet_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('dmo', 'Demo'), ('msc', 'Music'), ('wt', 'Walk Through'), ('ft', 'Full Teach')], default='dmo', max_length=3),
        ),
    ]
